# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: mysql2
  encoding: utf8
  database: lab_development
  pool: 20
  username: root
  password: 
  host: localhost
  port: 5432

test:
  adapter: mysql2
  encoding: utf8
  database: lab_test
  pool: 20
  username: root
  password: 
  host: localhost
  port: 5432

production:
  adapter: mysql2
  encoding: utf8
  database: lab_production
  pool: 20
  username: root
  password: 
  host: localhost
  port: 5432
